repos:
- repo: local
  hooks:
   # python: lint
   - id: ruff-check
     name: python lint
     entry: bash -c 'cd ./python && uv run ruff check --fix .'
     language: system
     types: [python]
     pass_filenames: false
   # python: format
   - id: ruff-format
     name: python format
     entry: bash -c 'cd ./python && uv run ruff format .'
     language: system
     types: [python]
     pass_filenames: false
   # python: type checking
   - id: ty check
     name: python type check
     entry: bash -c 'cd ./python && uv run ty check .'
     language: system
     types: [python]
     pass_filenames: false
   # rust: type checking
   - id: cargo check
     name: rust type check
     entry: bash -c 'cd ./rust && cargo check --all-targets --workspace'
     language: system
     types: [rust]
     pass_filenames: false
   # rust: format
   - id: cargo fmt
     name: rust format
     entry: bash -c 'cd ./rust && cargo fmt -- --check'
     language: system
     types: [rust]
     pass_filenames: false
